#Работа с API

In [1]:
import requests
import pandas as pd

In [2]:
base_url = "https://anapioficeandfire.com/api"

Получить информацию обо всех книгах и сохранить в pd.DataFrame

In [3]:
books = requests.get(f"{base_url}/books").json()

In [4]:
df_books = pd.DataFrame(books)
display(df_books)

,url,name,isbn,authors,numberOfPages,publisher,country,mediaType,released,characters,povCharacters
0,https://anapioficeandfire.com/api/books/1,A Game of Thrones,978-0553103540,[George R. R. Martin],694,Bantam Books,United States,Hardcover,1996-08-01T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
1,https://anapioficeandfire.com/api/books/2,A Clash of Kings,978-0553108033,[George R. R. Martin],768,Bantam Books,United States,Hardback,1999-02-02T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
2,https://anapioficeandfire.com/api/books/3,A Storm of Swords,978-0553106633,[George R. R. Martin],992,Bantam Books,United States,Hardcover,2000-10-31T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
3,https://anapioficeandfire.com/api/books/4,The Hedge Knight,978-0976401100,[George R. R. Martin],164,Dabel Brothers Publishing,United States,GraphicNovel,2005-03-09T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
4,https://anapioficeandfire.com/api/books/5,A Feast for Crows,978-0553801507,[George R. R. Martin],784,Bantam Books,United Status,Hardcover,2005-11-08T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
5,https://anapioficeandfire.com/api/books/6,The Sworn Sword,978-0785126508,[George R. R. Martin],152,Marvel,United States,Hardcover,2008-06-18T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
6,https://anapioficeandfire.com/api/books/7,The Mystery Knight,978-0765360267,[George R. R. Martin],416,Tor Fantasy,United States,Paperback,2011-03-29T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
7,https://anapioficeandfire.com/api/books/8,A Dance with Dragons,978-0553801477,[George R. R. Martin],1040,Bantam Books,United States,Hardcover,2011-07-12T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
8,https://anapioficeandfire.com/api/books/9,The Princess and the Queen,978-0765332066,[George R. R. Martin],784,Tor Books,United States,Hardcover,2013-12-03T00:00:00,[https://anapioficeandfire.com/api/characters/...,[]
9,https://anapioficeandfire.com/api/books/10,The Rogue Prince,978-0345537263,[George R. R. Martin],832,Bantam Books,United States,Hardcover,2014-06-17T00:00:00,[https://anapioficeandfire.com/api/characters/...,[]

Получить информацию обо всех домах Вестероса (Houses) и сохранить в pd.DataFrame

In [5]:
houses = requests.get(f"{base_url}/houses?pageSize=50").json()

df_houses = pd.DataFrame(houses)
display(df_houses)

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://anapioficeandfire.com/api/houses/1,House Algood,The Westerlands,"A golden wreath, on a blue field with a gold b...",,[],[],,,https://anapioficeandfire.com/api/houses/229,,,,[],[],[]
1,https://anapioficeandfire.com/api/houses/2,House Allyrion of Godsgrace,Dorne,"Gyronny Gules and Sable, a hand couped Or",No Foe May Pass,[],[Godsgrace],https://anapioficeandfire.com/api/characters/298,https://anapioficeandfire.com/api/characters/1922,https://anapioficeandfire.com/api/houses/285,,,,[],[],[https://anapioficeandfire.com/api/characters/...
2,https://anapioficeandfire.com/api/houses/3,House Amber,The North,,,[],[],,,,,,,[],[],[]
3,https://anapioficeandfire.com/api/houses/4,House Ambrose,The Reach,"Or, semy of ants gules",Never Resting,[],[],https://anapioficeandfire.com/api/characters/141,,https://anapioficeandfire.com/api/houses/398,,,,[],[],[https://anapioficeandfire.com/api/characters/...
4,https://anapioficeandfire.com/api/houses/5,House Appleton of Appleton,The Reach,"Or, an apple tree eradicated proper fructed gu...",,[],[Appleton],,,https://anapioficeandfire.com/api/houses/398,,,,[],[],[]
5,https://anapioficeandfire.com/api/houses/6,House Arryn of Gulltown,The Vale,,,[],[Gulltown],,,https://anapioficeandfire.com/api/houses/7,,,,[],[],[]
6,https://anapioficeandfire.com/api/houses/7,House Arryn of the Eyrie,The Vale,A sky-blue falcon soaring against a white moon...,As High as Honor,"[King of Mountain and Vale (formerly), Lord of...","[The Eyrie (summer), Gates of the Moon (winter)]",https://anapioficeandfire.com/api/characters/894,https://anapioficeandfire.com/api/characters/477,https://anapioficeandfire.com/api/houses/16,Coming of the Andals,https://anapioficeandfire.com/api/characters/144,,[],[https://anapioficeandfire.com/api/houses/6],[https://anapioficeandfire.com/api/characters/...
7,https://anapioficeandfire.com/api/houses/8,House Ashford of Ashford,The Reach,"Tenny, a sun in splendour beneath a chevron in...",Our Sun Shines Bright,[Lord of Ashford],[Ashford],,,https://anapioficeandfire.com/api/houses/398,,,,[],[],[https://anapioficeandfire.com/api/characters/...
8,https://anapioficeandfire.com/api/houses/9,House Ashwood,The North,,,[],[],,,https://anapioficeandfire.com/api/houses/34,,,,[],[],[]
9,https://anapioficeandfire.com/api/houses/10,House Baelish of Harrenhal,The Riverlands,"A field of silver mockingbirds, on a green fie...",,"[Lord Paramount of the Trident, Lord of Harren...",[Harrenhal],https://anapioficeandfire.com/api/characters/823,,https://anapioficeandfire.com/api/houses/16,299 AC,https://anapioficeandfire.com/api/characters/823,,[],[],[https://anapioficeandfire.com/api/characters/...
10,https://anapioficeandfire.com/api/houses/11,House Baelish of the Fingers,The Vale,"A grey stone head with fiery eyes, on a light ...",,[],[unnamed tower],https://anapioficeandfire.com/api/characters/823,,https://anapioficeandfire.com/api/houses/7,,https://anapioficeandfire.com/api/characters/1182,,[],[https://anapioficeandfire.com/api/houses/10],[https://anapioficeandfire.com/api/characters/...
11,https://anapioficeandfire.com/api/houses/12,House Ball,The Reach,Three white plates upon a chevron red on a whi...,,[],[],,,https://anapioficeandfire.com/api/houses/398,,,,[],[],[https://anapioficeandfire.com/api/characters/...
12,https://anapioficeandfire.com/api/houses/13,House Banefort of Banefort,The Westerlands,"A black hooded man, on a grey field, within a ...",,[Lord of Banefort],[Banefort],https://anapioficeandfire.com/api/characters/837,,https://anapioficeandfire.com/api/houses/229,,https://anapioficeandfire.com/api/characters/497,,[],[],[https://anapioficeandfire.com/api/characters/...
13,https://anapioficeandfire.com/api/houses/14,House Bar Emmon of Sharp Point,The Crownlands,"Fretty argent and white, a swordfish embowed h...",,[Lord of Sharp Point],[Sharp Point],https://anapioficeandfire.com/api/characters/332,,https://anapioficeandfire.com/api/houses/15,,,,[],[],[https://anapioficeandfire.com/api/characters/...
14,https://anapioficeandfire.com/api/houses/15,House Baratheon of Dragonstone,The Crownlands,"Or, a heart gules enflamed proper charged with...",,"[Lord of Dragonstone, King of Westeros]",[Dragonstone],https://anapioficeandfire.com/api/characters/1963,https://anapioficeandfire.com/api/characters/975,https://anapioficeandfire.com/api/houses/16,284 AC,https://anapioficeandfire.com/api/characters/1963,,[],[],[https://anapioficeandfire.com/api/characters/...
15,https://anapioficeandfire.com/api/houses/16,House Baratheon of King's Landing,The Crownlands,"A black crowned stag and a gold lion, combatan...",,[Lord of the Seven Kingdoms],[King's Landing],https://anapioficeandfire.com/api/characters/1029,https://anapioficeandfire.com/api/characters/775,,283 AC,https://anapioficeandfire.com/api/characters/901,,[],[],[https://anapioficeandfire.com/api/characters/...
16,https://anapioficeandfire.com/api/houses/17,House Baratheon of Storm's End,The Stormlands,"A black crowned stag, on a gold field(Or, a st...",Ours is the Fury,"[Lord of Storm's End, Lord Paramount of the St...","[Storm's End, Dragonstone (House Baratheon of ...",https://anapioficeandfire.com/api/characters/1029,https://anapioficeandfire.com/api/characters/775,https://anapioficeandfire.com/api/houses/16,1 AC,https://anapioficeandfire.com/api/characters/797,,[],"[https://anapioficeandfire.com/api/houses/15, ...",[https://anapioficeandfire.com/api/characters/...
17,https://anapioficeandfire.com/api/houses/18,House Beesbury of Honeyholt,The Reach,"Paly or and sable, on a pale of the last three...",Beware our Sting,[],[Honeyholt],https://anapioficeandfire.com/api/characters/1103,,https://anapioficeandfire.com/api/houses/195,,https://anapioficeandfire.com/api/characters/366,,[],[],[https://anapioficeandfire.com/api/characters/...
18,https://anapioficeandfire.com/api/houses/19,House Belmore of Strongsong,The Vale,"Six silver bells, 3, 2, 1, on a purple field(P...",,[Lord of Strongsong],[Strongsong],https://anapioficeandfire.com/api/characters/176,,https://anapioficeandfire.com/api/houses/7,,,,[],[],[https://anapioficeandfire.com/api/characters/...
19,https://anapioficeandfire.com/api/houses/20,House Bettley,The Westerlands,"Three blue beetles, on a gold field(Or, three ...",,[],[],,,https://anapioficeandfire.com/api/houses/229,,,,[],[],[https://anapioficeandfire.com/api/characters/...
20,https://anapioficeandfire.com/api/houses/21,House Bigglestone,The Riverlands,,,[],[],,,,,,,[],[],[]
21,https://anapioficeandfire.com/api/houses/22,House Blackbar of Bandallon,The Reach,"Argent, a fess sable",,[Lord of Bandallon],[Bandallon],,,https://anapioficeandfire.com/api/houses/398,,,,[],[],[https://anapioficeandfire.com/api/characters/...
22,https://anapioficeandfire.com/api/houses/23,House Blackfyre of King's Landing,,"Gules, a three headed dragon breathing flames ...",,[],[],,,https://anapioficeandfire.com/api/houses/378,184 AC,https://anapioficeandfire.com/api/characters/267,260 AC,[Blackfyre],[],[https://anapioficeandfire.com/api/characters/...
23,https://anapioficeandfire.com/api/houses/24,House Blackmont of Blackmont,Dorne,A black vulture with a pink infant in its claw...,,[],[Blackmont],https://anapioficeandfire.com/api/characters/1607,https://anapioficeandfire.com/api/characters/1574,https://anapioficeandfire.com/api/houses/285,,,,[],[],[https://anapioficeandfire.com/api/characters/...
24,https://anapioficeandfire.com/api/houses/25,House Blackmyre,The Neck,,,[],[],,,https://anapioficeandfire.com/api/houses/318,,,,[],[],[]
25,https://anapioficeandfire.com/api/houses/26,House Blacktyde of Blacktyde,Iron Islands,Vairy vert and sable,,[Lord of Blacktyde],[Blacktyde],,,https://anapioficeandfire.com/api/houses/169,,,,[],[],[https://anapioficeandfire.com/api/characters/...
26,https://anapioficeandfire.com/api/houses/27,House Blackwood of Raventree Hall,The Riverlands,A flock of ravens surrounding a black shield c...,,[Lord of Raventree],[Raventree Hall],https://anapioficeandfire.com/api/characters/2045,https://anapioficeandfire.com/api/characters/1241,https://anapioficeandfire.com/api/houses/10,Age of Heroes,,,[],[],[https://anapioficeandfire.com/api/characters/...
27,https://anapioficeandfire.com/api/houses/28,House Blanetree,The Riverlands,"Green and brown maple leaves, strewn across a ...",,[],[],,,https://anapioficeandfire.com/api/houses/395,,,,[],[],[https://anapioficeandfire.com/api/characters/...
28,https://anapioficeandfire.com/api/houses/29,House Blount,The Crownlands,A red bend sinister between two black porcupin...,,[],[],,,https://anapioficeandfire.com/api/houses/16,,,,[],[],[https://anapioficeandfire.com/api/characters/...
29,https://anapioficeandfire.com/api/houses/30,House Boggs,The North,,,[],[],,,https://anapioficeandfire.com/api/houses/318,,,,[],[],[]
30,https://anapioficeandfire.com/api/houses/31,House Boggs of Crackclaw Point,The Crownlands,,,[],[],,,https://anapioficeandfire.com/api/houses/16,,,,[],[],[https://anapioficeandfire.com/api/characters/...
31,https://anapioficeandfire.com/api/houses/32,House Bole,The North,,,[],[],,,https://anapioficeandfire.com/api/houses/150,,,,[],[],[]
32,https://anapioficeandfire.com/api/houses/33,House Bolling,The Stormlands,"Vairy orange and blue, upon a black canton, a ...",,[],[],,,https://anapioficeandfire.com/api/houses/17,,,,[],[],[https://anapioficeandfire.com/api/characters/...
33,https://anapioficeandfire.com/api/houses/34,House Bolton of the Dreadfort,The North,A red flayed man on pink de sang,Our Blades are Sharp,"[Red King (Age of Heroes), Lord of the Dreadfo...",[The Dreadfort],https://anapioficeandfire.com/api/characters/933,https://anapioficeandfire.com/api/characters/849,https://anapioficeandfire.com/api/houses/16,Age of Heroes,,,[],[],[https://anapioficeandfire.com/api/characters/...
34,https://anapioficeandfire.com/api/houses/35,House Borrell of Sweetsister,The Vale,"A white spider crab, on a grey-green field(Ver...",,[Lord of Sweetsister],[Breakwater in Sisterton],https://anapioficeandfire.com/api/characters/429,,https://anapioficeandfire.com/api/houses/370,,,,[],[],[https://anapioficeandfire.com/api/characters/...
35,https://anapioficeandfire.com/api/houses/36,House Botley of Lordsport,Iron Islands,"Vert, semy of fishes argent",,[Lord of Lordsport],[Lordsport],https://anapioficeandfire.com/api/characters/419,,https://anapioficeandfire.com/api/houses/169,,,,[],[],[https://anapioficeandfire.com/api/characters/...
36,https://anapioficeandfire.com/api/houses/37,House Bracken of Stone Hedge,The Riverlands,"A red stallion upon a gold shield, on a brown ...",,[],[Stone Hedge],https://anapioficeandfire.com/api/characters/1559,,https://anapioficeandfire.com/api/houses/10,Age of Heroes,,,[],[],[https://anapioficeandfire.com/api/characters/...
37,https://anapioficeandfire.com/api/houses/38,House Branch,The North,,,[],[],,,https://anapioficeandfire.com/api/houses/150,,,,[],[],[]
38,https://anapioficeandfire.com/api/houses/39,House Branfield,The North,,,[],[exiles living at Ironrath],,,,,,,[],[],[]
39,https://anapioficeandfire.com/api/houses/40,House Brax of Hornvale,The Westerlands,"A purple unicorn, on a silver field(Argent, a ...",,[],[Hornvale],https://anapioficeandfire.com/api/characters/1055,https://anapioficeandfire.com/api/characters/393,https://anapioficeandfire.com/api/houses/229,,,,[],[],[https://anapioficeandfire.com/api/characters/...
40,https://anapioficeandfire.com/api/houses/41,House Breakstone,The Vale,A red sledge,,[],[],,,,,,,[],[],[]
41,https://anapioficeandfire.com/api/houses/42,House Briar,Dorne,,,[High King of Dorne],[],,,,,,,[],[],[]
42,https://anapioficeandfire.com/api/houses/43,House Bridges,The Reach,A black stone bridge with three arches upon a ...,,[],[],,,https://anapioficeandfire.com/api/houses/398,,,,[],[],[]
43,https://anapioficeandfire.com/api/houses/44,House Brightstone,The Vale,,,[King of the Fingers],[],,,,,,Andal invasion,[],[],[]
44,https://anapioficeandfire.com/api/houses/45,House Brook,Dorne,,,[High King of Dorne],[],,,,,,,[],[],[]
45,https://anapioficeandfire.com/api/houses/46,House Broom,The Westerlands,"A silver helm crested with a sprig of broom, o...",,[],[],,,https://anapioficeandfire.com/api/houses/229,,,,[],[],[https://anapioficeandfire.com/api/characters/...
46,https://anapioficeandfire.com/api/houses/47,House Brownhill,Dorne,,,[High King of Dorne],[],,,,,,,[],[],[]
47,https://anapioficeandfire.com/api/houses/48,House Brune of Brownhollow,The Crownlands,"Argent, a bear's paw erased within a double tr...",,[The Knight of Brownhollow],[Brownhollow],https://anapioficeandfire.com/api/characters/184,,https://anapioficeandfire.com/api/houses/16,,,,[],[],[https://anapioficeandfire.com/api/characters/...
48,https://anapioficeandfire.com/api/houses/49,House Brune of the Dyre Den,The Crownlands,,,[Lord of the Dyre Den],[The Dyre Den],https://anapioficeandfire.com/api/characters/1380,,https://anapioficeandfire.com/api/houses/16,,,,[],[https://anapioficeandfire.com/api/houses/48],[https://anapioficeandfire.com/api/characters/...
49,https://anapioficeandfire.com/api/houses/50,House Buckler of Bronzegate,The Stormlands,"Three brass buckles, on a blue field(Azure, th...",,[],[Bronzegate],https://anapioficeandfire.com/api/characters/848,,https://anapioficeandfire.com/api/houses/17,,,,[],[],[https://anapioficeandfire.com/api/characters/...

Получить информацию обо всех домах Вестероса, у которых есть девиз, и сохранить в pd.DataFrame

In [6]:
houses_with_titles = requests.get(f"{base_url}/houses?pageSize=50&hasTitles=true").json()
df_houses_with_titles = pd.DataFrame(houses_with_titles)
display(df_houses_with_titles[["name", "titles"]].head())

,name,titles
0,House Arryn of the Eyrie,"[King of Mountain and Vale (formerly), Lord of..."
1,House Ashford of Ashford,[Lord of Ashford]
2,House Baelish of Harrenhal,"[Lord Paramount of the Trident, Lord of Harren..."
3,House Banefort of Banefort,[Lord of Banefort]
4,House Bar Emmon of Sharp Point,[Lord of Sharp Point]

#Работа с БД

In [7]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.10)

In [8]:
import psycopg2

In [9]:
host = "hh-pgsql-public.ebi.ac.uk"
port = 5432
database = "pfmegrnargs"
user = "reader"
password = "NWDMCE5xdipIjRrp"

In [10]:
try:
    conn = psycopg2.connect(dbname=database, user=user, password=password, host=host)
except:
    print('Can`t establish connection to database')

Получите 10 строк из таблицы rnc_database

In [11]:
with conn.cursor() as cursor:
  cursor.execute("SELECT display_name, num_sequences, num_organisms, url FROM rnc_database limit 10")
  rnc_database_10 = cursor.fetchall()

In [12]:
rnc_database_10[:2]

[('NONCODE', 234669, 7, 'http://www.noncode.org/'),
 ('VEGA', 0, 0, 'http://vega.sanger.ac.uk/')]

In [13]:
rnc_database_df = pd.DataFrame(rnc_database_10)
rnc_database_df.head()

         0         1       2                                   3
0  NONCODE    234669       7             http://www.noncode.org/
1     VEGA         0       0           http://vega.sanger.ac.uk/
2  GENCODE     47677       2            http://gencodegenes.org/
3      ENA  12086180  814855  https://www.ebi.ac.uk/ena/browser/
4     TAIR      4406       1         http://www.arabidopsis.org/